-- 코드를 작성해주세요

SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO I
JOIN FISH_NAME_INFO F ON I.FISH_TYPE = F.FISH_TYPE
WHERE I.FISH_TYPE IN (
    SELECT FISH_TYPE
    FROM FISH_NAME_INFO 
    WHERE FISH_NAME IN ('BASS', 'SNAPPER')
)